### ISSUE TITLE
File Structure?

### ISSUE THREAD

**Issue by dipamsen** [CodingTrain/Coding-Challenges#1]
I think we can/should start porting "non-p5 web editor" code from `CodingTrain/website` to here, otherwise the new website will have links to the old repo. 

That said, I would like to know if there is a preferred file structure to be followed in this repo for code examples.

**Comment by dipamsen** [comment]
I think this repo can be used for the following:
- **Processing/Other Language Ports** for the Coding Challenges
- **Processing/NodeJS/Other non-editor Code Examples** for linking to the video page

Most of the p5 Code can stay in the p5.js Web Editor for consistency

As you mentioned, some challenges can have dedicated repos (CodingTrain/Monty-Hall), whereas some might not be able to be ported to other languages. These may not have a folder in this repo.

**Comment by shiffman** [comment]
This all sounds great to me!!

**Comment by shiffman** [comment]
I think we can close this, yes? @dipamsen

**Comment by dipamsen** [comment]
Yes!
